 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/notifications", type: :request do
  
  # Notification. As you add validations to Notification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Notification.create! valid_attributes
      get notifications_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      notification = Notification.create! valid_attributes
      get notification_url(notification)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_notification_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      notification = Notification.create! valid_attributes
      get edit_notification_url(notification)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Notification" do
        expect {
          post notifications_url, params: { notification: valid_attributes }
        }.to change(Notification, :count).by(1)
      end

      it "redirects to the created notification" do
        post notifications_url, params: { notification: valid_attributes }
        expect(response).to redirect_to(notification_url(Notification.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Notification" do
        expect {
          post notifications_url, params: { notification: invalid_attributes }
        }.to change(Notification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post notifications_url, params: { notification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested notification" do
        notification = Notification.create! valid_attributes
        patch notification_url(notification), params: { notification: new_attributes }
        notification.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the notification" do
        notification = Notification.create! valid_attributes
        patch notification_url(notification), params: { notification: new_attributes }
        notification.reload
        expect(response).to redirect_to(notification_url(notification))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        notification = Notification.create! valid_attributes
        patch notification_url(notification), params: { notification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested notification" do
      notification = Notification.create! valid_attributes
      expect {
        delete notification_url(notification)
      }.to change(Notification, :count).by(-1)
    end

    it "redirects to the notifications list" do
      notification = Notification.create! valid_attributes
      delete notification_url(notification)
      expect(response).to redirect_to(notifications_url)
    end
  end
end
