# This file is not currently working, nor in use

services:
  web:
    build: ..
    # command: sleep infinity # Overrides default command so things don't shut down after the process ends.
    depends_on:
      - db
    env_file:
      - ../config/docker.env
    ports:
      - "3000:3000"
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - "../:/app"

  db:
    image: postgres:13
    env_file:
      - ../config/docker.env
    ports:
      - "5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  # Volume to hold the Postgres database on the host system
  data:
