name: Setup Development Environment for GitHub Copilot


# Automatically run the setup steps when they are changed to allow for easy validation, and
# allow manual testing through the repository's "Actions" tab
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    # Only let github read the repository contents
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup database
        env:
          POSTGRES_PASSWORD: password
        run: |
          bundle exec rails db:setup

      - name: Validate setup
        env:
          POSTGRES_PASSWORD: password
        run: |
          echo "Testing database connectivity..."
          bundle exec rails runner \
            "puts 'Database connection: OK'; \
            puts 'User count: ' + User.count.to_s"

          echo "Running code style validation..."
          bundle exec rubocop

          echo "Running test suite..."
          bundle exec rspec --format progress
